version: "2"
services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ./data:/website/data
  admin:
    build:
      context: ./
      dockerfile: ./admin/Dockerfile
    restart: unless-stopped
    ports:
      - "7000:7000"
